# Generated by Django 5.2.8 on 2025-12-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_alter_member_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
    ]
