# Generated by Django 5.2.8 on 2025-12-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='icon',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
